---
title: "Lab 2: Multiplexed 7-Segment Display and Keypad Row Scanning"
author: "Ishita Raje"
date: "9/16/2026"
---
# Introduction 
In this lab, I continued the modular FPGA design in Lab 1 by using the combinational seven-segment decoder module which allowed one hexadecimal value to be displayed and the parameterized counter module controlled. This allowed for this lab to focus on integrating a time-multiplexed dual display and a matrix-keypad scanner. 

The dual display helped show two independent hexadecimal values using one seven-segment decoder using one shared set of cathode signals. A counter rapidly alternated between the two display digits so that both appeared continuously illuminated.

The keypad scanner sequentially activated four rows with each signal toggling at 2 Hz. Additionally, NPN transistors were used to convert the FPGA row signals into open-collector outputs, while pull-up resistors helped define column logic levels. Red and green LEDs were used to indicate the active row and detected keypad column.

# Design and Testing Methodology
## Multiplexed Seven-Segment Display
The two common-anode display used one set of seven segment cathode signals that were conmnected in parallel to both digits of the display using the [datasheet] ((https://www.broadcom.com/products/leds-and-displays/7-segment/through-hole/hdsp-5721). The SystemVerilog code implemented a multiplexing counter output which selected one of the two four-bit switch inputs and passed it into the seven-segment decoder. The same counter output enabled the corresponding display digit. 

The seven-segment module from Lab 1 was reused without any modifications. The decoder contained combinational logic that translated a 4-bit hexadecimal input into an active-low seven-segment pattern. The multiplexer selection logic added to Lab 2 allowed for this decoder module to be used to take two different 4-bit inputs and serve both displays, displaying the corresponding hexadecimal value independently. 

A 2N3906 PNP transistor controlled both the common anode of each digit. These transistors were required because one FPGA output could not safely supply the combined current required when multiple segments were illuminated. Each segment required an individual current-limiting resistor and each PNP base required a resistor to limit current from the FPGA digit enable output.

Ultimately, the display multiplexing frequency needed to be fast enough to present viisble flickering while allowing the electrical signals to settle before the next digit was visible. Given that for human eyesight, a flcikering light blends into a solid image at ~60Hz, I chose a 96Hz (multiple of the high-speed oscillator on the FPGA) as the frequency to flash my digits at.

## Keypad Scanner

The keypad scanner was the main new module added in Lab 2. It reused an instance of the parameterized counter from Lab 1 and converted the counter state into the four required row patterns.

Each FPGA row outlet drove a 2N3904 NPN transistor configured as an open-collector output. When a row signal was asserted (based on the pre-assigned scanning pattern),the transistor turned on and pulled the corresponding row to low (ground or 0V). Whereas, when the signal was not asserted, the transistor turned off and left the row floating.

The open-collector circuit prevented two FPGA outputs from directly driving against each other when multiple keys were pressed. Each NPN transistor required a resistor between its base and the FPGA output to limit the base current.

Each keypad column was also connected to 3.3V (from the FPGA board) through a pull-up resistor. When no key is pressed, the pull-up resistor helps maintain a defined logic high value. Pressing the key connected the selected row to its correspodning columnm which caused a column to read logic low. 